arch:
  - amd64
  - ppc64le

language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.11"
  - "0.10"
jobs:
  exclude:
     - node_js: "0.10"
       arch: ppc64le
     - node_js: "0.11"
       arch: ppc64le
     - node_js: "0.12"
       arch: ppc64le

script:
  - npm install
  - npm test
